// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fkmonqbuaxjurenyutqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZrbW9ucWJ1YXhqdXJlbnl1dHF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNjM5NTgsImV4cCI6MjA3MzgzOTk1OH0.cpa3MVtYvgysqxvTEAQRa-Zl20obLetQnIsfrGej5tM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});